### ISSUE TITLE
Exporters fail to install

### ISSUE THREAD

**Issue by sudeephb** [canonical/hardware-observer-operator#253] opened 2024-05-30 10:28 UTC
On the edge channel, exporters fail to install. 
The install method should be triggered on installation [here](https://github.com/canonical/hardware-observer-operator/blob/862ac534a0d1c566084fae2a9b43b9f701796191/src/charm.py#L156).
The config files are present, but the service files are not.
Manually adding the same `exporter.install()` logic on another hook(eg. config-changed) installs the exporters successfully:
```
for exporter in self.exporters:
    exporter.install()
```
So there's nothing wrong with the installation logic inside the exporter service objects themselves.

**Comment by jneo8** [comment] 2024-05-31 08:55
Can you provide more details why the service file is not not there why first time install?

Also trigger exporter installation in another hook will break our life-cycle design, we should figure out why it's failing.

**Comment by sudeephb** [comment] 2024-06-03 08:31
While I'm still not sure of the exact cause, this seems like a race condition somewhere, as it doesn't occur everytime. I ran the hardware-dependent tests multiple times today, but this issue hasn't appeared at all.

**Comment by Pjack** [comment] 2024-06-14 06:25
We cannot reproduce it again so we close it after 2 weeks waiting.

**Closed by Pjack** 2024-06-14 06:25 UTC
